feat: useSnap hook, connected address
ChainSafe/aleo-snap pull request #44
Opened 2023-07-04 12:51 UTC by irubido

handles users not having metamask or metamask flask
useSnap hook
Closes #34

2023-07-04 13:55 UTC, BeroBurny requested changes

2023-07-04 13:55 UTC, BeroBurny commented on packages/example/src/hooks/useSnap.ts
> +const isDev = true;
Check out https://vitejs.dev/guide/env-and-mode.html#env-variables for `import.meta.env.DEV`

2023-07-04 13:55 UTC, BeroBurny commented on packages/example/src/components/AddSnap/AddSnap.tsx
> +  }, []);
maybe better to move this logic inside a snap, and add states like `isReady` for this kind of spinner

2023-07-04 13:55 UTC, BeroBurny commented on packages/example/src/hooks/useSnap.ts
> +  }, [snapInstalled]);
looks like it is better to split in 2 separate effects

2023-07-04 15:06 UTC, BeroBurny requested changes

2023-07-04 15:06 UTC, BeroBurny commented on packages/example/.env.sample
> +VITE_APP_SNAP_VERSION_NPM='1.0.5'
please do not use hardcoded version

2023-07-04 15:06 UTC, BeroBurny commented on packages/example/.env.sample
> +VITE_APP_IS_DEV=false
you have env that can help you with that!

2023-07-04 15:48 UTC, irubido commented
- vite dev always uses local snap origin

- vite build builds with npm snap origin
- vite build:local builds with local snap origin

2023-07-05 05:31 UTC, BeroBurny approved these changes

2023-07-05 05:31 UTC, merged